### ISSUE TITLE
Transaction broadcast error: 30549

### ISSUE THREAD

**Issue by eonwarped** [stoodkev/hive-keychain#68]
When posting currently with hive.blog, this is the error when broadcast. 

e.g. op 

```
[["comment",{"parent_author":"","parent_permlink":"test","author":"eonwarp","permlink":"3hta5m-test","title":"test","body":"test","json_metadata":"{\"tags\":[\"test\"],\"app\":\"hiveblog/0.1\",\"format\":\"markdown\"}"}],["comment_options",{"author":"eonwarp","permlink":"3hta5m-test","max_accepted_payout":"1000000.000 HBD","percent_hbd":10000,"allow_votes":true,"allow_curation_rewards":true,"extensions":[]}]]
```

Error in keychain background thread:

```
Error: transaction.operations = comment,[object Object],comment_options,[object Object]	 cause: comment_options.percent_steem_dollars = undefined	 cause: Illegal value: undefined (not an integer) 
 stack: TypeError: Illegal value: undefined (not an integer)
    at t.a.writeUint16 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:10:7309)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:5:23566)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:28485)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:6:3037)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:5:28533)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:28485)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30171)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30266)
    at Object.d.signTransaction (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:25342)
    at chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:28548
    at i (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:26734)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21144)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019)
    at o._resolveCallback (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:19880)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21299)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019)  
 stack: Error: comment_options.percent_steem_dollars = undefined	 cause: Illegal value: undefined (not an integer) 
 stack: TypeError: Illegal value: undefined (not an integer)
    at t.a.writeUint16 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:10:7309)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:5:23566)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:28485)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:6:3037)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:5:28533)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:28485)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30171)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30266)
    at Object.d.signTransaction (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:25342)
    at chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:28548
    at i (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:26734)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21144)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019)
    at o._resolveCallback (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:19880)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21299)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019) 
    at Function.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:31234)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:28604)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:6:3037)
    at Object.appendByteBuffer (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:5:28533)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:28485)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30171)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30266)
    at Object.d.signTransaction (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:25342)
    at chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:28548
    at i (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:26734)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21144)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019)
    at o._resolveCallback (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:19880)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21299)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019)
    at chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:2:30549 
    at Function.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:31234)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:28604)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30171)
    at t.value (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:13:30266)
    at Object.d.signTransaction (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:25342)
    at chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:16:28548
    at i (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:26734)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21144)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019)
    at o._resolveCallback (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:19880)
    at o._settlePromiseFromHandler (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21299)
    at o._settlePromise (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:21947)
    at o._settlePromise0 (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:22648)
    at o._settlePromises (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23978)
    at o._fulfill (chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:1:23019)
    at chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:2:30549
    at chrome-extension://jcacnejopjdphbnjgfaaobbfafkihpep/vendor/hive.min.js:4:26785
```

somehow still using percent steem dollars. This is on keychain version 1.10.2.2

**Comment by eonwarped** [comment]
It appears I need to refresh the rpc node and then it works. Perhaps this should be made more automatic.

**Comment by Cambridgeport90** [comment]
I had something like that happen to me recently as well, think it was either Thursday or Friday. I didn’t report it because I thought it was just me, posting something that was perhaps too long, or something.

**Comment by stoodkev** [comment]
Thanks for the reports, looking into it!
